### ISSUE TITLE
getParticipantById always returns local participant

### ISSUE THREAD

**Issue by szecsi** [Scarygami/dart_hangouts_api#2]
The problem appears to be
ar data = _makeProxyCall(["getLocalParticipant"], [participantId]);

at line 171, hangout.dart
instead of perhaps
ar data = _makeProxyCall(["getParticipantId"], [participantId]);

Is there a way for me to fix this locally (this is read only in Dart Editor)?

**Comment by Scarygami** [comment]
Fixed in https://github.com/Scarygami/dart_hangouts_api/commit/aa4859ca926a7e655e2f39e5e42af1224fde167c

I also pushed a new version 0.2.2 to pub.

**Comment by szecsi** [comment]
Thank you for the fix and also for the library. Dart is so much more enabling for me than JS.
